config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  post '/session/signin', to: 'sessions#signin'
  get '/session/signout', to: 'sessions#signout'
  
  get '/home', to: 'application#home'
  get '/about', to: 'application#about'
  get '/account', to: 'application#account'
  get '/profile/:profile_id', to: 'application#profile', as: 'profile'
  get '/following', to: 'application#following'
  get '/followers', to: 'application#followers'
  post '/search', to: 'application#search'

  namespace :api do
    namespace :v1 do
      resources :feed, only: [:index]
      resources :users, only: [:index, :create, :show, :update, :destroy] do
        resources :posts, only: [:index, :create, :destroy]
        resources :relationships, only: [:create, :destroy]
        resources :notifications, only: [:index, :update, :destroy]

        get '/following_list', to: 'relationships#following_list'
        get '/followers_list', to: 'relationships#followers_list'
        delete '/follower_delete/:profile_id', to: 'relationships#follower_delete'
        get '/relationship_test/:profile_id', to: 'relationships#test', as: 'relationship_test'
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < BaseController

  before_action :force_authenticate, except: [:index, :profile, :about]

  def index
    if !is_authenticated?
      render :index
    else
      redirect_to home_path
    end
  end

  def home
    render :home
  end

  def search
    @users = User.where("name like ? or email like ?", "%#{params[:search][:query]}%", "%#{params[:search][:query]}%")
    render :search
  end

  def account
    render :account
  end

  def profile
    @profile = User.where(id: params[:profile_id]).first

    render :profile
  end

  def following
    render :following
  end

  def followers
    render :followers
  end

  def about
    render :about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="col-md-7">
      <h1 class="start-title"><%= t('pages.about.title') %></h1>
      <%= raw t('pages.about.description') %>
    </div>
  </div>
</div>

app/views/application/account.html.erb
<div class="account-page col-md-6 col-md-offset-3" ng-controller="AccountController">
  <div class="row">
    <div class="col-md-12">
      <h2><%= t('pages.account.titles.account') %></h2>
      <div class="panel panel-default">
        <div class="panel-body p10">
          <div class="media">
            <div class="media-left">
              <img ngf-thumbnail="account.avatar || '<%= @current_user.avatar.url(:thumb) %>'">
            </div>
            <div class="media-body">
            <p class="account-name text-primary"><strong><%= @current_user.name %></strong></p>
            <p class="account-email text-muted"><%= @current_user.email %></p>
            <p class="account-bio mb0"><%= @current_user.bio %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="alert alert-sm alert-success" ng-show="success"><%= t('pages.account.forms.messages.success') %></div>
      
      <%= form_for(:user, :url => api_v1_user_path(@current_user.id), :method => :put, :html => {:class => 'account-form', 'ng-submit' => 'proccess($event)'}) do |f| %>
        <h2><%= t('pages.account.titles.informations') %></h2>
        <div class="panel panel-default">
          <div class="panel-body p10">
            <div class="form-group">
              <button class="change-photo btn btn-sm btn-success" ngf-select ng-model="account.avatar" ngf-pattern="'image/*'" ngf-accept="'image/*'"><%= t('pages.account.forms.buttons.select') %></button>
              <ul class="errors-list text-danger" ng-show="showErrors">
                <li class="errors-list-item" ng-repeat="error in errors.avatar">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <%= f.text_field(:name, :class => 'form-control input-sm', :value => @current_user.name, :placeholder => t('forms.placeholders.name'), 'ng-model' => 'account.name', 'ng-init' => "account.name = '#{@current_user.name}'") %>
              <ul class="errors-list text-danger" ng-show="showErrors">
                <li class="errors-list-item" ng-repeat="error in errors.name">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <%= f.text_area(:bio, :class => 'form-control input-sm', :value => @current_user.bio, :placeholder => t('forms.placeholders.bio'), 'ng-model' => 'account.bio', 'ng-init' => "account.bio = '#{@current_user.bio}'") %>
              <ul class="errors-list text-danger" ng-show="showErrors">
                <li class="errors-list-item" ng-repeat="error in errors.bio">{{error}}</li>
              </ul>
            </div>
          </div>
        </div>
        
        <h2><%= t('pages.account.titles.password') %></h2>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="form-group">
              <%= f.email_field(:email, :class => 'form-control input-sm', :value => @current_user.email, :placeholder => t('forms.placeholders.email'), 'ng-model' => 'account.email', 'ng-init' => "account.email = '#{@current_user.email}'") %>
              <ul class="errors-list text-danger" ng-show="showErrors">
                <li class="errors-list-item" ng-repeat="error in errors.email">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <%= f.password_field(:password, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.password'), 'ng-model' => 'account.password') %>
              <ul class="errors-list text-danger" ng-show="showErrors">
                <li class="errors-list-item" ng-repeat="error in errors.password">{{error}}</li>
              </ul>
            </div>
            <div class="form-group mb0 clearfix">
              <%= f.button(t('pages.account.forms.buttons.save'), :type => :submit, :class => 'btn btn-sm btn-primary pull-right') %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/application/followers.html.erb
<div class="account-page col-md-6 col-md-offset-3" ng-controller="FollowersController">
  <div class="row">
    <div class="col-md-12">
      <h2><%= t('pages.followers.title') %></h2>

      <div class="panel panel-default" ng-show="showNoUsers">
        <div class="panel-body p10">
          <p class="mb0"><%= t('pages.followers.messages.any') %></p>
        </div>
      </div>
      
      <div class="panel panel-default" ng-repeat="relationship in relationships">
        <div class="panel-body p10">
          <div class="media">
            <div class="media-left">
              <img ng-src="{{relationship.user.avatar}}">
            </div>
            <div class="media-body">
              <p class="account-name text-primary">
                <a href="/profile/{{relationship.user.id}}">
                  <strong>{{relationship.user.name}}</strong>
                </a>
              </p>
              <p class="account-email text-muted">{{relationship.user.email}}</p>
              <p class="account-bio">{{relationship.user.bio}}</p>
              <button class="btn btn-sm btn-danger" ng-show="relationship.test" ng-click="updateRelationship(relationship)"><%= t('pages.followers.buttons.unfollow') %></button>
              <button class="btn btn-sm btn-success" ng-show="!relationship.test" ng-click="updateRelationship(relationship)"><%= t('pages.followers.buttons.follow') %></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/following.html.erb
<div class="account-page col-md-6 col-md-offset-3" ng-controller="FollowingController">
  <div class="row">
    <div class="col-md-12">
      <h2><%= t('pages.following.title') %></h2>

      <div class="panel panel-default" ng-show="showNoUsers">
        <div class="panel-body p10">
          <p class="mb0"><%= t('pages.following.messages.any') %></p>
        </div>
      </div>
      
      <div class="panel panel-default" ng-repeat="relationship in relationships">
        <div class="panel-body p10">
          <div class="media">
            <div class="media-left">
              <img ng-src="{{relationship.user.avatar}}">
            </div>
            <div class="media-body">
              <p class="account-name text-primary">
                <a href="/profile/{{relationship.user.id}}">
                  <strong>{{relationship.user.name}}</strong>
                </a>
              </p>
              <p class="account-email text-muted">{{relationship.user.email}}</p>
              <p class="account-bio">{{relationship.user.bio}}</p>
              <button class="btn btn-sm btn-danger" ng-show="relationship.test" ng-click="updateRelationship(relationship)"><%= t('pages.following.buttons.unfollow') %></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/home.html.erb
<div class="home-page col-md-6 col-md-offset-3" ng-controller="FeedController">
	<div class="row">
		<div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body p10">
          <%= form_for(:search, :url => search_path, :html => {:class => 'search-form'}) do |f| %>
            <div class="col-xs-6 pl0">
              <p class="mb0 search-label"><%= t('pages.home.forms.search.label') %></p>
            </div>
            <div class="col-xs-4 pr0">
              <div class="form-group mb0">
                <%= f.search_field(:query, :class => 'form-control input-sm', :placeholder => t('pages.home.forms.search.placeholder')) %>
              </div>
            </div>
            <div class="col-xs-2 pr0">
              <div class="form-group mb0">
                <%= f.button(t('pages.home.forms.search.button'), :type => :submit, :class => 'search-button btn btn-sm btn-primary') %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
			<div class="panel panel-default">
        <div class="panel-body">
          <ul class="errors-list text-danger" ng-show="showErrors">
            <li class="errors-list-item" ng-repeat="error in errors.content">{{error}}</li>
          </ul>
          <%= form_for(:post, :url => api_v1_user_posts_path(@current_user['id']), :html => {:class => 'posts-form', 'ng-submit' => 'proccess($event)'}) do |f| %>
            <%= f.hidden_field(:user_id, :value => @current_user['id'], 'ng-model' => 'post.user_id', 'ng-init' => "post.user_id = #{@current_user['id']}", :class => 'user_id') %>
            <div class="form-group">
              <%= f.text_area(:content, :class => 'form-control input-sm', :placeholder => t('pages.home.forms.post.placeholder'), 'ng-model' => 'post.content', 'ng-change' => 'verify()') %>
            </div>
            <div class="form-group mb0">
              <div class="row">
                <div class="col-xs-8">
                  {{70-post.content.length}} <%= t('pages.home.forms.post.remaining') %>
                </div>
                <div class="col-xs-4">
                  <%= f.button(t('pages.home.forms.post.button'), :type => 'submit', :class => 'btn btn-sm btn-primary pull-right') %>
                </div>
              </div>
            </div>
          <% end %>
        </div>   
      </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
        <div class="panel-body p10">
          <ul class="posts-list" ng-show="posts.length > 0">
            <li class="posts-list-item" ng-repeat="post in posts">
              <div class="post media">
                <div class="media-left">
                  <img ng-src="{{post.user.avatar}}" alt="{{post.user.name}}">
                </div>
                <div class="media-body">
                  <p class="post-date text-muted">{{date(post.created_at)}}</p>
                  <p class="post-author text-primary">
                    <a href="/profile/{{post.user.id}}" title="Perfil de {{post.user.name}}">
                      <strong>{{post.user.name}}</strong>
                    </a>
                  </p>
                  <p class="post-content">{{post.content}}</p>
                  <p class="post-links mb0">
                    <a class="text-danger" href="javascript:;" ng-click="delete(post)" ng-show="current_user_id == post.user.id"><%= t('pages.home.links.delete') %></a>
                  </p>
                </div>
              </div>
            </li>
          </ul>
          <ul class="posts-list" ng-show="posts.length == 0">
            <li class="posts-list-item">
              <div class="post">
                <p class="post-content mb0"><%= t('pages.home.messages.any') %></p>
              </div>
            </li>
          </ul>
        </div>   
      </div>

      <div class="alert alert-sm alert-success" ng-show="showTotalHets">
        <%= t('pages.home.messages.all') %>
      </div>

      <button class="load-more btn btn-sm btn-success" ng-click="more()" ng-show="showLoadMore"><%= t('pages.home.links.more') %></button>
		</div>
	</div>
</div>

app/views/application/index.html.erb
<div class="start-page col-md-10 col-md-offset-1">
  <div class="row">
    <div class="col-md-7">
      <h1 class="start-title"><%= t('pages.start.title') %></h1>
      <p class="start-description"><%= t('pages.start.description') %></p>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <div class="sign-panel panel panel-default" ng-controller="SigninController">
        <div class="panel-body">
          <h2 class="sign-title"><%= t('pages.start.forms.titles.signin') %></h2>
          <div class="sign-alert alert alert-danger" role="alert" ng-show="errors">
            <%= t('pages.start.forms.messages.errors') %>
          </div>
          <%= form_for(:user, :url => session_signin_path, :html => {:class => 'signin-form', 'ng-submit' => 'process($event)'}) do |f| %>
            <div class="form-group">
              <%= f.email_field(:email, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.name'), 'ng-model' => 'user.email') %>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-8 pr0">
                  <%= f.password_field(:password, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.password'), 'ng-model' => 'user.password') %>
                </div>
                <div class="col-sm-4">
                  <%= f.button(t('pages.start.forms.buttons.signin'), :type => 'submit', :class => 'sign-btn btn btn-sm btn-primary') %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="sign-panel panel panel-default" ng-controller="SignupController">
        <div class="panel-body">
          <h2 class="sign-title"><%= t('pages.start.forms.titles.signup') %></h2>
          <div class="sign-alert alert alert-success" role="alert" ng-show="success">
            <%= t('pages.start.forms.messages.success') %>
          </div>
          <%= form_for(:user, :url => api_v1_users_path, :html => {:class => 'signup-form', 'ng-submit' => 'process($event)'}) do |f| %>
            <div class="form-group">
              <%= f.text_field(:name, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.name'), 'ng-model' => 'user.name') %>
              <ul class="sign-errors-list" ng-repeat="error in errors.name">
                <li class="sign-errors-list-item text-danger">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <%= f.email_field(:email, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.email'), 'ng-model' => 'user.email') %>
              <ul class="sign-errors-list" ng-repeat="error in errors.email">
                <li class="sign-errors-list-item text-danger">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-8 pr0">
                  <%= f.password_field(:password, :class => 'form-control input-sm', :placeholder => t('forms.placeholders.password'), 'ng-model' => 'user.password') %>
                  <ul class="sign-errors-list" ng-repeat="error in errors.password">
                    <li class="sign-errors-list-item text-danger">{{error}}</li>
                  </ul>
                </div>
                <div class="col-sm-4">
                  <%= f.button(t('forms.buttons.send'), :type => 'submit', :class => 'sign-btn btn btn-sm btn-primary') %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/profile.html.erb
<input class="profile_id" type="hidden" value="<%= @profile.id %>">

<div class="account-page col-md-6 col-md-offset-3" ng-controller="ProfileController">
  <div class="row">
    <div class="col-md-12">
      <h2><%= t('pages.profile.title') %></h2>
      <div class="panel panel-default">
        <div class="panel-body p10">
          <div class="media">
            <div class="media-left">
              <img ngf-thumbnail="account.avatar || '<%= @profile.avatar.url(:thumb) %>'">
            </div>
            <div class="media-body">
              <p class="account-name text-primary"><strong><%= @profile.name %></strong></p>
              <p class="account-email text-muted"><%= @profile.email %></p>
              <p class="account-bio"><%= @profile.bio %></p>
              <% if @current_user and @current_user.id != @profile.id %>
                <button class="btn btn-sm btn-danger" ng-show="relationship.test" ng-click="updateRelationship()"><%= t('pages.profile.buttons.unfollow') %></button>
                <button class="btn btn-sm btn-success" ng-show="!relationship.test" ng-click="updateRelationship()"><%= t('pages.profile.buttons.follow') %></button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body p10">
          <ul class="posts-list" ng-show="posts.length > 0">
            <li class="posts-list-item" ng-repeat="post in posts">
              <div class="post media">
                <div class="media-left">
                  <img ng-src="{{post.user.avatar}}" alt="{{post.user.name}}">
                </div>
                <div class="media-body">
                  <p class="post-date text-muted">{{date(post.created_at)}}</p>
                  <p class="post-author text-primary">
                    <strong>{{post.user.name}}</strong>
                  </p>
                  <p class="post-content">{{post.content}}</p>
                  <p class="post-links mb0">
                    <a class="text-danger" href="javascript:;" ng-click="delete(post)" ng-show="current_user_id == post.user.id"><%= t('pages.profile.links.delete') %></a>
                  </p>
                </div>
              </div>
            </li>
          </ul>
          <ul class="posts-list" ng-show="posts.length == 0">
            <li class="posts-list-item">
              <div class="post">
                <p class="post-content mb0"><%= t('pages.profile.messages.any') %></p>
              </div>
            </li>
          </ul>
        </div>   
      </div>

      <div class="alert alert-sm alert-success" ng-show="showTotalHets">
        <%= t('pages.profile.messages.all') %>
      </div>

      <button class="load-more btn btn-sm btn-success" ng-click="more()" ng-show="showLoadMore"><%= t('pages.profile.links.more') %></button>
    </div>
  </div>
</div>

app/views/application/search.html.erb
<div class="account-page col-md-6 col-md-offset-3">
  <div class="row">
    <div class="col-md-12">
      <h2><%= t('pages.search.messages.all') %>: <i><%= params[:search][:query] %></i></h2>
      
      <% if @users.size > 0 %>
        <% @users.each do |user| %>
          <div class="panel panel-default">
            <div class="panel-body p10">
              <div class="media">
                <div class="media-left">
                  <%= image_tag user.avatar.url(:avatar) %>
                </div>
                <div class="media-body">
                  <p class="account-name text-primary">
                    <%= link_to profile_path(user.id) do%>
                      <strong><%= user.name %></strong>
                    <% end %>
                  </p>
                  <p class="account-email text-muted"><%= user.email %></p>
                  <p class="account-bio"><%= user.bio %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="panel panel-default">
          <div class="panel-body p10">
            <p class="mb0"><%= t('pages.search.messages.any') %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>