config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  post '/session/signin', to: 'sessions#signin'
  get '/session/signout', to: 'sessions#signout'
  
  get '/home', to: 'application#home'
  get '/about', to: 'application#about'
  get '/account', to: 'application#account'
  get '/profile/:profile_id', to: 'application#profile', as: 'profile'
  get '/following', to: 'application#following'
  get '/followers', to: 'application#followers'
  post '/search', to: 'application#search'

  namespace :api do
    namespace :v1 do
      resources :feed, only: [:index]
      resources :users, only: [:index, :create, :show, :update, :destroy] do
        resources :posts, only: [:index, :create, :destroy]
        resources :relationships, only: [:create, :destroy]
        resources :notifications, only: [:index, :update, :destroy]

        get '/following_list', to: 'relationships#following_list'
        get '/followers_list', to: 'relationships#followers_list'
        delete '/follower_delete/:profile_id', to: 'relationships#follower_delete'
        get '/relationship_test/:profile_id', to: 'relationships#test', as: 'relationship_test'
      end
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="HetsApp" ng-cloak>
  <head>
    <title><%= t('title') %></title>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid" data-no-turbolink>
      <div class="row">
        <div class="topbar clearfix">
          <ul class="topbar-list left">
            <li class="topbar-list-item">
              <%= link_to root_path do %>
                <i class="fa fa-home"></i> <%= t('menu.home') %>
              <% end %>
            </li>
            <li class="topbar-list-item">
              <%= link_to about_path do %>
              <i class="fa fa-newspaper-o"></i> <%= t('menu.about') %>
              <% end %>
            </li>
          </ul>

          <% if @current_user %>
            <ul class="topbar-list right">
              <li class="topbar-list-item text-success">
                <%= t('menu.hello') %>, <%= @current_user['name'] %>!
              </li>
              <li class="topbar-list-item">
                <%= link_to home_path do %>
                  <i class="fa fa-feed"></i> <%= t('menu.feed') %>
                <% end %>
              </li>
              <li class="topbar-list-item">
                <%= link_to following_path do %>
                  <i class="fa fa-bookmark"></i> <%= t('menu.following') %>
                <% end %>
              </li>
              <li class="topbar-list-item">
                <%= link_to followers_path do %>
                  <i class="fa fa-bookmark-o"></i> <%= t('menu.followers') %>
                <% end %>
              </li>
              <li class="topbar-list-item">
                <%= link_to account_path do %>
                  <i class="fa fa-user"></i> <%= t('menu.account') %>
                <% end %>
              </li>
              <li class="topbar-list-item" ng-controller="NotificationsController">
                <a href="javascript:;" ng-click="openNotifications()">
                  <i class="fa fa-globe"></i> <%= t('menu.notifications') %> <span class="badge" ng-show="new_notifications_count > 0">{{new_notifications_count}}</span>
                </a>
                <div class="notifications panel panel-default" ng-show="showNotifications">
                  <div class="panel-body p0">
                    <ul class="notifications-list" ng-show="notifications.length > 0">
                      <li class="notifications-list-item p10" ng-class="!notification.read ? 'bg-success text-success' : ''" ng-repeat="notification in notifications">
                        <p class="notification-date mb0 text-muted">{{date(notification.created_at)}}</p>
                        <p class="notification-message mb0">{{notification.message}}</p>
                        <p class="notification-links mb0">
                          <a href="javascript:;" ng-click="update(notification)"><i class="fa fa-check"></i></a>
                          <a class="text-danger" href="javascript:;" ng-click="delete(notification)"><i class="fa fa-close"></i></a>
                        </p>
                      </li>
                    </ul>
                    <ul class="notifications-list" ng-show="notifications.length == 0">
                      <li class="notifications-list-item p10 bg-danger text-danger">
                        <p class="notification-message mb0">Você não possui nenhuma notificação</p>
                      </li>
                    </ul>
                  </div>
                </div>
              </li>
              <li class="topbar-list-item">
                <%= link_to session_signout_path do %>
                  <i class="fa fa-sign-out"></i> <%= t('menu.signout') %>
                <% end %>
              </li>
            </ul>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
    <script>
      <% if @current_user %>
        var current_user_id = "<%= @current_user.id %>";
      <% else %>
        var current_user_id = -1;
      <% end %>
    </script>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/danialfarid-angular-file-upload/10.1.14/ng-file-upload-shim.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/danialfarid-angular-file-upload/10.1.14/ng-file-upload.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  </body>
</html>